---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading and preprocessing the data
```{r loading}
library(ggplot2)
library(dplyr)
amd <- read.csv("activity.csv") ##Activity Monitoring Data(amd)
## Checking the data
dim(amd)

str(amd)

head(amd)

tail(amd)

## checking the missing values
missing_amd <- amd[is.na(amd$steps),]
dim(missing_amd)
```

## What is mean total number of steps taken per day?
```{r hist}
##Total number of steps(tns)
##Calculate the total number of steps taken per day
tns <- with(amd, tapply(amd$steps, as.factor(amd$date), sum, na.rm = TRUE))

##Make a histogram of the total number of steps taken each day
hist(tns, main = "Histogram of total number of steps taken per day", xlab = "Total number of steps")

##Calculate and report the mean and median of the total number of steps taken per day
summary(tns)
```

## What is the average daily activity pattern?
```{r avg}
##Make a time series plot (i.e. type = “l”) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

mean_steps <- with(amd, tapply(amd$steps, amd$interval, mean,na.rm = TRUE))
interval <- levels(as.factor(amd$interval))
plot(interval, mean_steps, type = "l", main = "Time series plot of the \n average number of steps taken", xlab = "interval", ylab = "Mean steps")

##Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

table <- data.frame(mean_steps, interval)
table[table$mean_steps==max(table$mean_steps),][2]

```

## Imputing missing values
```{r imputing}
##Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

length(missing_amd$steps)

##Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

mean_steps <- with(amd, tapply(amd$steps, amd$interval, mean,na.rm = TRUE))
missing_amd$steps <- mean_steps

#Create a new dataset that is equal to the original dataset but with the missing data filled in.
new_dt <- rbind(amd, missing_amd)
new_dt <- new_dt[order(new_dt$date), ]

##Total number of steps with replaced missing values(tns2)
tns2 <- with(new_dt, tapply(steps, as.factor(new_dt$date), sum))
#Make a histogram of the total number of steps taken each day
hist(tns2, main = "Histogram of total number of steps taken per day", xlab = "Total number of steps")

##Mean and median total number of steps taken per day WITHOUT filling in the missing values
summary(tns)

##Mean and median total number of steps taken per day WITH filling in the missing values
summary(tns2)

```

## Are there differences in activity patterns between weekdays and weekends?
```{r differences}
new_dt <- mutate(new_dt, days = weekdays(as.Date(new_dt$date)))
### find weekend features in the dataset
weekend_feature <- grep("Saturday|Sunday", new_dt$days, ignore.case = TRUE)
### subset data of the weekend
weekend_dt <- new_dt[weekend_feature, ]
weekend_dt$weekday <- "weekend"

### subset data of the weekday
weekday_dt <- subset(new_dt,new_dt$days!=weekend_feature)

weekday_dt$weekday <- "weekday"

## create a new dataset containing 2 new variable "days" and weekday" 
## - days: indicates the days in the week
## - weekday: indicate the days are at the "weekend" or "weekday"
new_dt2 <- rbind(weekday_dt, weekend_dt)

##Panel plot showing the comparative variation of mean steps during weekdays and weekends
new_dt2$fact <- levels(as.factor(new_dt2$weekday))
mean_number_steps <- aggregate(steps~ interval+fact, new_dt2, mean)
g <- qplot(interval, steps, data = mean_number_steps, facets = fact~.)
g + geom_line(size = 1) + ylab("Mean steps") + ggtitle("Average number of steps taken, \n averaged across all weekday days or weekend days ")

```
